//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahead.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB1 : DbContext
    {
        public DB1()
            : base("name=DB1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AskLeaf> AskLeaves { get; set; }
        public virtual DbSet<ForumActivity> ForumActivities { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ReviewItem> ReviewItems { get; set; }
        public virtual DbSet<SupportAgentInProduct> SupportAgentInProducts { get; set; }
        public virtual DbSet<SupportAgentInTeam> SupportAgentInTeams { get; set; }
        public virtual DbSet<SupportAgentScenario> SupportAgentScenarios { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<SupportAgent> SupportAgents { get; set; }
    }
}
