//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ahead.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportAgent
    {
        public int ID { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Chinese { get; set; }
        public Nullable<System.DateTime> OnBoard_Date { get; set; }
        public string ForHCTracking { get; set; }
        public string Sub_Func { get; set; }
        public string Project { get; set; }
        public string Team { get; set; }
        public Nullable<System.DateTime> GoLive_Date { get; set; }
        public Nullable<double> Phone_Number { get; set; }
        public string DeliverMSDN { get; set; }
        public string DeliverSO { get; set; }
        public string DeliverASPNET { get; set; }
    }
}
